In [255]:
import numpy as np

In [256]:
a = np.array([1, 2, 3, 4], dtype=np.int8) # 1D
print(a)

[1 2 3 4]


In [257]:
b = np.array([
    [1.1, 2.2, 3.3],
    [4.4, 5.5, 6.6]
]) # 2D is list in a list ...keep doing it for more dimenssions
print(b)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [258]:
print(f"a.ndim= {a.ndim}  ,  b.ndim= {b.ndim}")

a.ndim= 1  ,  b.ndim= 2


In [259]:
print(f"a.shape= {a.shape}  ,  b.shape= {b.shape}")

a.shape= (4,)  ,  b.shape= (2, 3)


In [260]:
print(f"a.dtype= {a.dtype}  ,  b.dtype= {b.dtype}")

a.dtype= int8  ,  b.dtype= float64


In [261]:
print(f"a.itemsize= {a.itemsize} bytes  ,  b.itemsize= {b.itemsize} bytes")

a.itemsize= 1 bytes  ,  b.itemsize= 8 bytes


In [262]:
print(f"a.size= {a.size} elements  ,  b.size= {b.size} elements")

a.size= 4 elements  ,  b.size= 6 elements


In [263]:
print(f"a.nbytes= {a.nbytes} bytes  ,  b.nbytes= {b.nbytes} bytes")

a.nbytes= 4 bytes  ,  b.nbytes= 48 bytes


In [264]:
print(f"a.nbytes= {a.size} * {a.itemsize} = {a.size*a.itemsize} bytes  ,  b.nbytes= {b.size} * {b.itemsize} = {b.size*b.itemsize} bytes")

a.nbytes= 4 * 1 = 4 bytes  ,  b.nbytes= 6 * 8 = 48 bytes


In [265]:
a = np.array([
    [1, 2, 3 , 4 , 5 , 6 , 7],
    [8, 9, 10, 11, 12, 13, 14]
])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [266]:
# get element form array [row, col]
a[1, 5] # row 2, col 6 (starts at 0)

13

In [267]:
# C-style (this is uncouth)
a[1][5]

13

In [268]:
# get first row with all cols
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [269]:
# get a column
a[:,2]

array([ 3, 10])

In [270]:
# slice and select
a[0, 1:-1:2]

array([2, 4, 6])

In [271]:
# assign anything, just keep the shape
b = a
b[1,:] = [-1, -2, -3, -4, -5, -6, -7]
print(b)

[[ 1  2  3  4  5  6  7]
 [-1 -2 -3 -4 -5 -6 -7]]


In [272]:
c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [273]:
c.shape

(2, 2, 2)

In [274]:
c.size

8

In [275]:
c.ndim

3

In [276]:
# work outside in to access 
c[0, 1, 1]

4

In [277]:
c[0,:,:]

array([[1, 2],
       [3, 4]])

In [278]:
d = c
d[1,:,:] = [[-1, -2], [-3, -4]] # just match the size and it will assign
print(d)

[[[ 1  2]
  [ 3  4]]

 [[-1 -2]
  [-3 -4]]]


## some initializing

In [279]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [280]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [281]:
np.ones(3)

array([1., 1., 1.])

In [282]:
np.ones((5,5), dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [283]:
np.full(a.shape, 99, dtype=np.int32) # fill with value (needs a shape parameter)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]], dtype=int32)

In [284]:
np.full_like(a, 77) # use shape of existing (no shape parameter)

array([[77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77]])

In [285]:
np.random.rand(3,2)

array([[0.59067834, 0.51357064],
       [0.22072565, 0.70326453],
       [0.35634301, 0.5869152 ]])

In [286]:
np.random.randn(3,5)

array([[-0.43214759, -2.02828545,  1.58189222,  0.61918572, -0.12615447],
       [-0.878599  ,  0.89780703,  1.32898007,  0.77479177,  1.69145206],
       [-1.02029572,  1.27037069,  0.40411866,  1.94403568,  0.73241012]])

In [287]:
np.random.random_sample(a.shape)

array([[0.2529264 , 0.31334801, 0.07489161, 0.1235339 , 0.68412456,
        0.62223821, 0.11339931],
       [0.25612567, 0.34448766, 0.15320443, 0.78141133, 0.5131961 ,
        0.25426477, 0.81122787]])

In [288]:
np.random.randint(7) # one number [0:6]

3

In [289]:
np.random.randint(90, 101, size=(3,3)) # start, stop, fill-size

array([[ 95,  99,  98],
       [100,  97,  90],
       [ 92, 100,  91]])

In [290]:
np.identity(4, dtype=np.int8) # identy matrix is always square

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [291]:
arr = np.array([1, 2, 3], dtype=np.int32)
rep = np.repeat(arr, 3) # repeat the array
print(rep)

[1 1 1 2 2 2 3 3 3]


In [292]:
arr = np.array([[1, 2, 3]], dtype=np.int32) # force 2D array
rep = np.repeat(arr, 3, axis=0) # repeat the array on axis
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## array initializing building

In [293]:
outp = np.ones((5,5), dtype=np.int16) # build all 1's
print(outp)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [294]:
z = np.zeros((3,3), dtype=np.int16) # get the 0's section
z[1,1] = 9
print(z)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [295]:
# put it together to get what you want
outp[1:-1, 1:-1] = z
print(outp)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# be careful copying

In [296]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [297]:
b[0] = 999
print(a) # you effected "a" because it was a shallow copy (they both pointed to same thing)

[999   2   3]


In [298]:
# do this instead
c = np.array([5, 6, 7], dtype=np.int8)
d = c.copy()
d[0] = 1
print(f"{c}\n{d}") # .copy() made the deep copy

[5 6 7]
[1 6 7]


## basic math with numpy

In [299]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [300]:
a+2

array([3, 4, 5, 6])

In [301]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [302]:
a+=2
print(a)
a -= 2

[3 4 5 6]


In [303]:
a**2

array([ 1,  4,  9, 16])

In [304]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [305]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [306]:
# linear algebra typically involves using the entire matrix, not element-wise
A = np.ones((2,3))
B = np.full((3,2),2)
np.matmul(A,B)

array([[6., 6.],
       [6., 6.]])

In [307]:
C = np.identity(3)
np.linalg.det(C) # identity has det==1

1.0

In [308]:
A1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
A2 = np.max(A1, axis=1).sum()
print(A2)

15


## reorganize array

In [309]:
before = np.array([
    [1,2,3,4],
    [5,6,7,8]
], dtype=np.int32)
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [310]:
before.reshape((4,2)) # anything, just has to have same elementsb

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)

In [311]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)

In [312]:
# buiding
v1 = np.array([1,2,3,4], dtype=np.int8)
v2 = np.array([5,6,7,8], dtype=np.int8)
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [313]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [314]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1, h2]) # horizontal stacking still has to keep dimension

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## loading data

In [315]:
dat = np.genfromtxt('gendata.txt', delimiter=',', dtype=np.int32)
print(dat)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 26 28 29 30]]


In [316]:
dat > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [317]:
temp = dat[dat > 20]
print(temp)

[21 22 23 24 25 26 26 28 29 30]


In [318]:
a = np.array([1,2,3,4,5,6,7], dtype=np.int32)
a[[0,3,-1]] # pass a list to get index values

array([1, 4, 7], dtype=int32)

In [319]:
np.any(dat>20, axis=1)

array([False, False,  True])

In [320]:
np.all(~(dat <=10) & (dat >0), axis=1)

array([False,  True,  True])

In [322]:
test = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]  
])
test[2:4,0:2]  # start included, stop is not

array([[11, 12],
       [16, 17]])

In [324]:
stuff = []
stop = 4
for x in range(0,stop) :
    row = x
    col = x + 1
    stuff.append(test[row, col])
np.array(stuff)  # eww

array([ 2,  8, 14, 20])

In [325]:
# do this instead... 2 difffernt list
test[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [328]:
test[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])