In [2]:
import numpy as np
import sys

In [3]:
a = np.array([1,2,3,4]) # library will pick the datatype for you

In [4]:
b = np.array([0, 0.5, 1, 1.2, 2])

In [5]:
a[0], a[1] # get some elements

(1, 2)

In [6]:
a[0:]   # first element to end

array([1, 2, 3, 4])

In [7]:
b[[0, 2, -1]] # first, third, and last element (another numpy array)

array([0., 1., 2.])

In [8]:
b[0], b[2], b[-1] # first, third, and last element (same, but tupple)

(0.0, 1.0, 2.0)

In [9]:
a.dtype # it does this because of platform you are on

dtype('int64')

In [10]:
b.dtype # there was a floating point number

dtype('float64')

# Multi Dimension

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"(rows,cols):{A.shape}  ,  ndim:{A.ndim}  ,  elements:{A.size}  ,  dtype:{A.dtype}")

(rows,cols):(3, 3)  ,  ndim:2  ,  elements:9  ,  dtype:int64


In [25]:
A[1] # picks 2nd row

array([4, 5, 6])

In [26]:
A[1,2] # row 1, col 2  (prefered, good for slicing)

6

In [27]:
A[1][2] # row 1, col 2 (c-style)

6

In [28]:
A[0:2] # select up to last row (all cols)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A[:,:2] # select all rows, up to last column

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
A[0] = np.array([97, 98, 99], dtype=A.dtype) # reassign first row, dimensions must match
print(A)

[[97 98 99]
 [ 4  5  6]
 [ 7  8  9]]


In [32]:
A[2,2] = 66 # assign a single element
print(A)

[[97 98 99]
 [ 4  5  6]
 [ 7  8 66]]


In [18]:
# dimensions must match
B = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(f"(depth,rows,cols):{B.shape}  ,  ndim:{B.ndim}  ,  elements:{B.size}  ,  dtype:{B.dtype}")

(depth,rows,cols):(2, 3, 4)  ,  ndim:3  ,  elements:24  ,  dtype:int64


In [33]:
B.sum()

300

In [34]:
B.mean()

12.5

In [35]:
B.std()

6.922186552431729

In [36]:
B.sum(axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])