In [1]:
import numpy as np 

In [2]:
a = np.arange(4) # array range
print(a)

[0 1 2 3]


In [3]:
a + 10 # adds to all elements, immutable

array([10, 11, 12, 13])

In [4]:
a * 10 # multiply to all elements, immutable

array([ 0, 10, 20, 30])

In [5]:
a += 2 # increment all elements by 2, mutable (broadcast operation)
print(a)

[2 3 4 5]


In [6]:
l = [0, 1, 2, 3] # pure python list

In [7]:
[i * 10 for i in l] # 10x comprehension

[0, 10, 20, 30]

In [10]:
b = np.array([3, 3, 3, 3])

In [11]:
a+b

array([5, 6, 7, 8])