In [1]:
import numpy as np

# Boolean arrays (similar operations)

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
# broadcast boolean (not scalable, but say what you want to select)
a[[False, False, True, True]] # select last 2 elements

array([2, 3])

In [4]:
# this is where the utility of the boolean comes in
a >= 2

array([False, False,  True,  True])

In [5]:
# use it to make a sub array, filters the numeric arrays
a[a>1]

array([2, 3])

In [8]:
a[a < a.mean()]

array([0, 1])

In [10]:
# use regular operators
a[(a == 2) & (a < 5)]

array([2])

In [11]:
a[(a==1) | (a==3)]

array([1, 3])