In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [3]:
A.dot(B) # multiplication

array([[20, 14],
       [56, 41],
       [92, 68]])

In [4]:
A @ B # better multiplication

array([[20, 14],
       [56, 41],
       [92, 68]])

In [5]:
np.matmul(A, B) # ok multiplicaiton

array([[20, 14],
       [56, 41],
       [92, 68]])

In [6]:
B.T # easy transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [7]:
np.transpose(B) # long transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [12]:
l = list(range(99999999))
npArr = np.arange(99999999)

In [13]:
%time np.sum(npArr ** 2) # < 1 sec with numpy

CPU times: user 381 ms, sys: 270 ms, total: 650 ms
Wall time: 668 ms


652921401952298879

In [14]:
%time sum([x ** 2 for x in l]) # over 20 sec with pure python

CPU times: user 11.1 s, sys: 6.08 s, total: 17.2 s
Wall time: 19.6 s


333333318333333549999999